#!/usr/bin/perl
use Cwd qw/abs_path/;
use Getopt::Long;
use File::Spec;
my $abs_path = abs_path($0);
$abs_path=~ s/(.*)\/([\w\.]+)/$1/;
require "$abs_path/eda_subroutines.pl";
#####################################################################
#Copyright : Copyright (C) 2016 Parallella Foundation
#License   : MIT
#Author    : Andreas Olofsson
#####################################################################
#use strict;
my %libhash;
my %cellhash;
my $Usage =<<EOF;

======================================================================
Usage : aif2netlist -aif <AIF Format Chip Bump File>
                    -bga <BGA signal mapping>
                    -mh  <Mirror Die Horizontal>
                    -mv  <Mirror Die Vertical> 
======================================================================
EOF

my $result =  GetOptions('aif:s', 'bga:s', 'mv:s', 'mh:s');
if((!defined $opt_aif) || (!defined $opt_bga)){
  print "$Usage";               
  exit;
}

#Need to flip die for flip-chip
if(defined $opt_mv){
    $mv = -1;
}else{
    $mv = 1;
}
if(defined $opt_mh){
    $mh = -1;
}else{
    $mh = 1;
}

###############################
#Reading in BGA
###############################
($bgaref,$size)=&read_csv($opt_bga);
%bga=%$bgaref;

foreach $row (keys %bga){
    foreach $col (keys %{$bga{$row}}){
	if($col > 0 && $row > 0){
	    $col2 = sprintf("%02d", $col);
	    $row2 = sprintf("%02d", $row);
	    $ball = "B$row2$col2";
	    #push ball into array
	    push(@{$balls{$bga{$row}{$col}}},$ball);
	}
    }
}

###############################
#Reading in AIF
###############################

open(FILE,"$opt_aif");
while(<FILE>){
    if(/\;/){
	#comment
    } elsif(/^WIDTH\=(.*)/){
	$width = $1;
    } elsif(/HEIGHt\=(.*)/){
	$height = $1;
    } elsif(/^([\w\[\]]+)\s+([\w\[\]]+)\s+([\w\[\]]+)\s+([\d\.\-]+)\s+([\d\.\-]+)/){
	$netlist{$2}{"net"} = $1;
	$netlist{$2}{"x"}   = $mh * $4;
	$netlist{$2}{"y"}   = $mv * $5;
	@{$netlist{$2}{"balls"}}=@{$balls{$netlist{$2}{net}}};
    }
}
close(FILE);

###############################
#Write Out Netlist
###############################
print "SIGNAL, BUMP,DIE-X, DIE-Y, BGA-BALLS\n";
foreach $bump (sort keys %netlist){
    if( @{$netlist{$bump}{balls}} > 0 ) {
	print "$netlist{$bump}{net},$bump,$netlist{$bump}{x},$netlist{$bump}{y},@{$netlist{$bump}{balls}}\n";
    }
}


