#!/usr/bin/perl
#####################################################################
#Copyright : Copyright (C) 2016 Parallella Foundation
#License   : MIT
#Author    : Andreas Olofsson
#####################################################################
#use strict
use Getopt::Long;
use File::Spec;
my $Usage =<<EOF;
======================================================================
Function   : Converts LEF to Proprietary Format (MW)

Usage      : lef2lib -tf  <TechnologyFile> 
                     -lef <LEF File> 
                     -ma  <LEF Mapping File> 
                     -l   <Library name>
                     -f   <Format>          

Example    : lef2lib -tf 3nm.tf -lef sram.lef -map lef.map -l "MWLIB"
======================================================================
EOF
my $result =  GetOptions('tf:s','lef:s','map:s', 'l:s', 'f:s' );
if((!defined $opt_tf)||(!defined $opt_lef)||(!defined $opt_map)||(!defined $opt_l)){
  print "$Usage";               
  exit;
}   

system("touch /tmp/tech.lef");
open(FILE,">/tmp/libprep.tcl");
print FILE "extend_mw_layers\n";
print FILE "create_mw_lib -technology $opt_tf $opt_l\n";
print FILE "read_lef -lib_name $opt_n -tech_lef_files \"/tmp/tech.lef\" -layer_mapping \"$opt_map\" -cell_lef_files \"$opt_lef\"\n"; 
print FILE "exit\n";
close(FILE);
#system("Milkyway -galaxy -nogui -tcl -log read_lef.log -file libprep.tcl");
close(FILE);
system("rm /tmp/libprep.tcl");
system("rm /tmp/tech.lef");
