#!/usr/bin/perl
#####################################################################
#Author    : Andreas Olofsson
#License   : ??
#####################################################################
#use strict
use Getopt::Long;
use File::Spec;
my $Usage =<<EOF;
======================================================================
Function   : Converts LEF to MW
Usage      : lef2mw -tf  <TechnologyFile> 
                    -lef <LEF> 
                    -map <LEFMAP> 
                    -n   <NAME>          
Example    : lef2mw -tf 3nm.tf -lef sram.lef -map lef.map -n "MWLIB"
======================================================================
EOF
my $result =  GetOptions('tf:s','lef:s','map:s', 'n:s' );
if((!defined $opt_tf)||(!defined $opt_lef)||(!defined $opt_map)||(!defined $opt_n)){
  print "$Usage";               
  exit;
}   

system("touch tech.lef");
open(FILE,">libprep.tcl");
print FILE "extend_mw_layers\n";
print FILE "create_mw_lib -technology $opt_tf $opt_n\n";
print FILE "read_lef -lib_name $opt_n -tech_lef_files \"tech.lef\" -layer_mapping \"$opt_map\" -cell_lef_files \"$opt_lef\"\n"; 
print FILE "exit\n";
close(FILE);
system("Milkyway -galaxy -nogui -tcl -log read_lef.log -file libprep.tcl");
