#!/usr/bin/perl
#####################################################################
#Copyright : Copyright (C) 2016 Parallella Foundation
#License   : MIT
#Author    : Andreas Olofsson
#####################################################################
#use strict
use Getopt::Long;
use File::Spec;
my $Usage =<<EOF;
======================================================================
Function   : Extracts information from SRAM compiler data dump
Usage      : sram_data -f <SRAM Memory Compiler Data Reference> 
           : (if data is in pdf, use pdf2totext -layer first)         
Example    : sram_data -f "data.txt" -t "blah, blah"
======================================================================
EOF
my $result =  GetOptions('f:s', 't:s');
if((!defined $opt_f) || (!defined $opt_t)){
  print "$Usage";               
  exit;
}   
open(FILE,"$opt_f");
printf("%10s %10s %10s %10s %10s %10s %10s %10s %10s %10s\n", "CORNER","WORDS", "IO", "SEG", "AREA", "PERIOD", "READC", "WRITEC", "LEAKAGE", "OPTION");
while(<FILE>){
    if(/^\s+((tt|ff|ss)\w+)/){    
	$Corner = $1;
    }
    elsif(/$opt_t/){
	@List=split(' ', $_);
	printf("%10s %10s %10s %10s %10s %10s %10s %10s %10s %10s\n", $Corner,@List[1],@List[2],@List[3],@List[5],@List[7],@List[12],@List[13],@List[17],@List[18]);
    }
}
