#!/usr/bin/perl
#####################################################################
#Copyright : Copyright (C) 2016 Parallella Foundation
#License   : MIT
#Author    : Andreas Olofsson
#####################################################################
#use strict
use Getopt::Long;
use File::Spec;
my $REV = "3.11.2.25";
my $Usage =<<EOF;
======================================================================
Function   : Extracts LEF layers from Synopsys technology file      
             (Assumes LEF layer name matches technology layer name) 
Usage      : tf2map -tf <TechnologyFilee>                            
Example    : tf2map -tf "blah.tf" > lef.map
======================================================================
EOF
my $result =  GetOptions('tf:s');
if((!defined $opt_tf)){
  print "$Usage";               
  exit;
}   
open(FILE,"$opt_tf");
while(<FILE>){
    if(/Layer\s+\"(\w+)\"/){
	$Layer=$1;
    }
    elsif(/layerNumber\s+\=\s*(\d+)/){
	$Number=$1;
	print "$Layer $Number\n";
    }
}
